services:
  nginx:
    build: 
      context: ./nginx
    volumes:
      - 'wordpress-files:/var/www/html'
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - TZ=UTC

  php:
    build:
      context: ./php
    volumes:
      - 'wordpress-files:/var/www/html'
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - TZ=UTC
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}

  cli:
    image: wordpress:cli
    volumes:
      - 'wordpress-files:/var/www/html'
    user: "33:33"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - TZ=UTC
    depends_on:
      - php
    restart: no
    entrypoint: ["/bin/sh"]
