services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html:ro
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        content: |
          server {
              listen 80;
              root /var/www/html;
              index index.php index.html;

              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-XSS-Protection "1; mode=block" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header Referrer-Policy "no-referrer-when-downgrade" always;
              add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;

              real_ip_header X-Forwarded-For;
              set_real_ip_from 172.16.0.0/12;
              real_ip_recursive on;

              gzip on;
              gzip_vary on;
              gzip_min_length 1024;
              gzip_proxied expired no-cache no-store private auth;
              gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/javascript application/xml;
              gzip_disable "MSIE [1-6]\.";

              location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
                  expires 365d;
                  add_header Cache-Control "public, no-transform";
              }

              location = /favicon.ico {
                  log_not_found off;
                  access_log off;
              }

              location = /robots.txt {
                  allow all;
                  log_not_found off;
                  access_log off;
              }

              location ~ /\. {
                  deny all;
                  access_log off;
                  log_not_found off;
              }

              location ~* ^/wp-content/uploads/.*.(html|htm|shtml|php|js|swf)$ {
                  deny all;
              }

              location / {
                  try_files $uri $uri/ /index.php?$query_string;
              }

              location ~ \.php$ {
                  fastcgi_pass php:9000;
                  fastcgi_index index.php;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  fastcgi_param PATH_INFO $fastcgi_path_info;
                  fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
                  fastcgi_param HTTP_X_REAL_IP $remote_addr;
                  fastcgi_buffers 16 16k;
                  fastcgi_buffer_size 32k;
                  include fastcgi_params;
                  fastcgi_read_timeout 300;
              }

              error_page 404 /404.html;
              error_page 500 502 503 504 /50x.html;
          }
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - TZ=UTC

  php:
    image: wordpress:php8.1-fpm
    volumes:
      - ./src:/var/www/html
      - type: bind
        source: ./php/php.ini
        target: /usr/local/etc/php/conf.d/custom.ini
        content: |
          memory_limit = 256M
          upload_max_filesize = 64M
          post_max_size = 64M
          max_execution_time = 300
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - TZ=UTC
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

  cli:
    image: wordpress:cli
    volumes:
      - ./src:/var/www/html
    user: "33:33"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - TZ=UTC
    depends_on:
      - php

